[docs]  Redesigned Selectors
AlexanderMoskovkin/testcafe-phoenix pull request #5
Opened 2016-11-23 10:29 UTC by AlexanderMoskovkin

2016-11-23 12:50 UTC, helen-dikareva requested changes
/r-

2016-11-23 12:50 UTC, helen-dikareva commented on docs/articles/documentation/test-api/selecting-page-elements/selectors.md
> +`child(cssSelector)` | Finds all parents of all nodes in the matching set and filters them by `cssSelector`.
oops, `parents`. The same below.

2016-11-23 12:50 UTC, helen-dikareva commented on docs/articles/documentation/test-api/selecting-page-elements/selectors.md
> +Finds second parents (parent of parent) of `.container` elements. Peeks first element in the matching set. Then in that element finds elements that matches '.someClass' selector. Filter them by text
May be '.someClass' should be highlighted like `.container`

2016-11-23 12:50 UTC, helen-dikareva commented on docs/articles/documentation/test-api/selecting-page-elements/selectors.md
> +	const div    = await Selector('.myDiv')();
formating

2016-11-23 12:50 UTC, helen-dikareva commented on docs/articles/documentation/test-api/selecting-page-elements/selectors.md
> +> Important! ***deprecated*** *Will be removed in next releases. Use [selectors](link) and [property shorthands](link) to obtain values.*
We can add first link yet

2016-11-26 19:54 UTC, lexkazakov commented on docs/articles/documentation/test-api/selecting-page-elements/selector-options.md
> +If you need to call a selector from a Node.js callback, assign the current
To call a selector from a Node.js callback, assign the current [test controller](../test-code-structure.md#test-controller) to the `boundTestRun` option.

2016-11-26 20:22 UTC, lexkazakov commented on docs/articles/documentation/test-api/selecting-page-elements/selector-options.md
> +> Important! ***deprecated*** *Will be removed in next releases. Use [withText()](selectors.md#filter-multiple-dom-nodes) to filter elements by text.*
***Deprecated.*** *Use the [withText()](selectors.md#filter-multiple-dom-nodes) method to filter elements by text content or a regular expression that matches this content. The [options.text](#optionstext) option will be removed in future releases.*

2016-11-26 20:26 UTC, lexkazakov commented on docs/articles/documentation/test-api/selecting-page-elements/selector-options.md
> +> Important! ***deprecated*** *Will be removed in next releases. Use [nth()](selectors.md#filter-multiple-dom-nodes) to filter elements by its index.*
***Deprecated.*** *Use the [nth()](selectors.md#filter-multiple-dom-nodes) method to select a node by its index. The [options.index](#optionsindex) option will be removed in future releases.*

2016-11-26 20:38 UTC, lexkazakov commented on docs/articles/documentation/test-api/selecting-page-elements/selectors.md
> +    // when you pass it to an action or an assertion or execute it.
// This selector will return the first matching DOM node.
// You can execute this selector or pass it as a parameter to an action or assertion.

2016-11-26 20:40 UTC, alcazaco commented on docs/articles/documentation/test-api/selecting-page-elements/selectors.md
>      // This selector is created from a function that returs all elements of a specified class.
// This selector is created from a function that retur_n_s all visible elements of a specified class.

2016-11-26 20:49 UTC, lexkazakov commented on docs/articles/documentation/test-api/selecting-page-elements/selectors.md
> +    // The selector additionally requires the returned element to become visible.
[Remove this comment]

2016-11-26 20:55 UTC, lexkazakov commented on docs/articles/documentation/test-api/selecting-page-elements/selectors.md
> +    const elemWithClass = Selector(cl => document.getElementsByClassName(cl), {
[Kazakov: Rename it to accent that selector returns *multiple* elements]

const elementsWithClass = Selector(cl => document.getElementsByClassName(cl), {

2016-11-26 20:58 UTC, lexkazakov commented on docs/articles/documentation/test-api/selecting-page-elements/selectors.md
> +    const fourthElemWithClass = Selector(thirdElemWithClass, { visibilityCheck: false });
[Kazakov: the previous selector was renamed, so rename the current one.]
const hiddenElementsWithClass = Selector(elementsWithClass, { visibilityCheck: false });

2016-11-26 21:27 UTC, lexkazakov commented on docs/articles/documentation/test-api/selecting-page-elements/selectors.md
> +Functions and CSS selector strings which initialize a selector can have one matching DOM element on the page, several or nothing.
Functions and CSS selector strings that initialize a selector may return a single matching DOM element on the page, multiple elements or nothing.

2016-11-26 21:38 UTC, alcazaco commented on docs/articles/documentation/test-api/selecting-page-elements/selectors.md
> +Selector provides the following properties to check this:
You can use the following Selector properties to check whether the matching elements exist or get a number of them.

2016-11-26 22:04 UTC, lexkazakov commented on docs/articles/documentation/test-api/selecting-page-elements/selectors.md
> +Selector api provides methods that can be combined together, making flexible functional-style selector system.
The selector API provides methods that can be combined together, thus providing you with a flexible functional-style selector mechanism.

2016-11-26 22:06 UTC, alcazaco commented on docs/articles/documentation/test-api/selecting-page-elements/selectors.md
> +Selector provides methods to filter DOM nodes by its index and text:
Selector provides methods to filter DOM nodes by their index or text:

2016-11-26 22:09 UTC, lexkazakov commented on docs/articles/documentation/test-api/selecting-page-elements/selectors.md
> +`nth(index)` | Selector | Creates selector for `index` element in the matching set.
Creates selector that return an element by its index in the matching set.

2016-11-26 22:10 UTC, lexkazakov commented on docs/articles/documentation/test-api/selecting-page-elements/selectors.md
> +`withText(text)` | Selector | Creates selector that filters matching set by given `text`.
Creates selector that filters matching set by the specified `text`.

2016-11-26 22:10 UTC, lexkazakov commented on docs/articles/documentation/test-api/selecting-page-elements/selectors.md
> +`withText(re)` | Selector | Creates selector that filters matching set by given regular expression `re`.
Creates selector that filters matching set using the specified regular expression.

2016-11-26 22:14 UTC, alcazaco commented on docs/articles/documentation/test-api/selecting-page-elements/selectors.md
> +Selector provide methods to find elements by DOM hierarchy in jQuery-style.
The selector API provides methods to find elements within a DOM hierarchy in jQuery style.

2016-11-26 22:19 UTC, lexkazakov commented on docs/articles/documentation/test-api/selecting-page-elements/selectors.md
> +`find(cssSelector)` | Finds all descendants of all nodes in the matching set and filters them either by CSS selector.
Finds all descendants of all nodes in the matching set and filters them by specified CSS selector.

2016-11-26 22:20 UTC, lexkazakov commented on docs/articles/documentation/test-api/selecting-page-elements/selectors.md
> +`find(filterFn)` | Finds all descendants of all nodes in the matching set and filters them using `filterFn`. `filterFn` is a client function predicate that receives node.
Finds all descendants of all nodes in the matching set and filters them using `filterFn`. `filterFn` is a client function predicate that receives a node.

2016-11-26 22:21 UTC, lexkazakov commented on docs/articles/documentation/test-api/selecting-page-elements/selectors.md
> +`child(filterFn)` | Finds all child elements (not nodes) of all nodes in the matching set and filters them by `filterFn`. `filterFn` is a client function predicate that receives node.
`filterFn` is a client function predicate that receives a node.

2016-11-26 22:22 UTC, alcazaco commented on docs/articles/documentation/test-api/selecting-page-elements/selectors.md
> +`sibling(cssSelector)` | Finds all sibling  of all nodes in the matching set and filters them by `cssSelector`.
Finds all sibling elements (not nodes) of all nodes in the matching set and filters them by `cssSelector`.

2016-11-26 22:23 UTC, lexkazakov commented on docs/articles/documentation/test-api/selecting-page-elements/selectors.md
> +`sibling(filterFn)` | Finds all sibling  of all nodes in the matching set and filters them by `filterFn`. `filterFn` is a client function predicate that receives node.
Finds all sibling elements (not nodes) of all nodes in the matching set and filters them by `filterFn`. `filterFn` is a client function predicate that receives a node.

2016-11-27 13:44 UTC, lexkazakov commented on docs/articles/documentation/test-api/selecting-page-elements/selectors.md
> +Finds all `ul` elements on page. Then in each found `ul` element finds `label` elements. Then for each `label` element finds parent that matches  `div.someClass` selector.
formatting

2016-11-27 14:06 UTC, lexkazakov commented on docs/articles/documentation/test-api/selecting-page-elements/selectors.md
> +Note that if selector initializer has several matching DOM nodes on the page the selector execution returns the first one from the set.
Note that if a selector initializer has several matching DOM nodes on the page, the selector returns the first node from the matching set.

2016-11-27 14:12 UTC, lexkazakov commented on docs/articles/documentation/test-api/selecting-page-elements/selectors.md
> +> Important! ***deprecated*** *Will be removed in next releases. Use [selectors](#creating-selectors) instead.*
***Deprecated*** *Use [selectors](#creating-selectors) instead. The `select` method of the [test controller](../test-code-structure.md#test-controller) will be removed in future releases.*

2016-11-27 14:14 UTC, lexkazakov commented on docs/articles/documentation/test-api/selecting-page-elements/selectors.md
> +Note that if selector initializer has several matching DOM nodes on the page the action will be executed for the first one from the set.
Note that if a selector initializer has multiple matching DOM nodes on the page, the action will be executed only for the first node from the matching set.

2016-11-27 14:17 UTC, lexkazakov commented on docs/articles/documentation/test-api/selecting-page-elements/selectors.md
> +You can check is a DOM node has an expected state by passing [snapshot API shorthand](#snapshot-api-shorthands) directly to [test actions](../assertions/index.md).
You can check whether a particular DOM node has an expected state by passing [snapshot API shorthand](#snapshot-api-shorthands) directly to [test actions](../assertions/index.md).

2016-11-27 14:21 UTC, lexkazakov commented on docs/articles/index.html
> +                <p>You can access webpage elements in different ways (by css selector, text, DOM hierarchy or use any custom logic) with <a href="documentation/test-api/selecting-page-elements/select
[translate:] It provides you with rich capabilities for writing test scripts.

2016-11-28 08:37 UTC, lexkazakov commented on docs/articles/documentation/test-api/selecting-page-elements/selector-options.md
> +> Important! ***deprecated*** *Will be removed in next releases. Use [hierarchical selectors](selectors.md#find-elements-by-dom-hierarchy).*
***Deprecated*** *Use [hierarchical selectors](selectors.md#find-elements-by-dom-hierarchy). The `option.dependencies` will be removed in future releases.*

2016-11-28 16:39 UTC, closed without merging